apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test and build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://node:20.0-alpine3.17
        name: Build
        run: npm install && npm run build
